#!/usr/bin/env bash
# Radeon Cloud / ROCm helper — does NOT silently pip-install CUDA torch.
set -euo pipefail
cd "$(dirname "$0")/.."

echo "==> Character Workshop ROCm setup"
echo ""
echo "Step 0 — Check GPU hardware"
echo "  rocm-smi || true"
echo ""
echo "Step 1 — Check current torch (must NOT be +cu*)"
echo "  python3 -c \"import torch; print(torch.__version__, torch.cuda.is_available(), getattr(torch.version,'hip',None))\""
echo ""
echo "Step 2 — If you see +cu* or cuda_available False after pip, REMOVE CUDA stack:"
echo "  python3 -m pip uninstall -y torch torchvision torchaudio"
echo "  python3 -m pip freeze | grep -iE 'nvidia-|cuda-toolkit|triton' | cut -d= -f1 | xargs -r python3 -m pip uninstall -y"
echo ""
echo "Step 3 — Install ROCm PyTorch (pick index matching your ROCm; examples):"
echo "  # Check ROCm: cat /opt/rocm/.info/version 2>/dev/null"
echo "  python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2"
echo "  # If 6.2 fails, try rocm6.1 / rocm6.3 per https://pytorch.org/get-started/locally/"
echo ""
echo "Step 4 — Verify"
echo "  python3 -c \"import torch; assert torch.cuda.is_available(); print(torch.__version__, torch.version.hip, torch.cuda.get_device_name(0))\""
echo ""
echo "Step 5 — App deps WITHOUT pulling CUDA torch"
echo "  python3 -m pip install -r requirements.txt"
echo "  python3 -m pip install 'accelerate>=0.33.0' --no-deps"
echo "  python3 -m pip install psutil packaging 2>/dev/null || true"
echo "  # Re-check torch is still +rocm:"
echo "  python3 -c \"import torch; print(torch.__version__, torch.cuda.is_available())\""
echo ""
echo "Step 6 — Models + run"
echo "  bash scripts/download_models.sh"
echo "  export MOCK=0 && python3 app.py"
echo ""
echo "Done (this script only prints instructions)."
